name: Tests

on:
  push:
    branches: [ main, master ]

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pretix-sumup-payment
    permissions:
      id-token: write
    steps:
      # retrieve your distributions here
      - run: make
      - run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
