name: Code Style

on:
  push:
    paths-ignore:
      - 'pretix_sumup/locale/**'
      - 'pretix_sumup/static/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'pretix_sumup/locale/**'
      - 'pretix_sumup/static/**'

jobs:
  style:
    name: style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pretix
        run: pip3 install pretix
      - name: Install Dependencies
        run: pip3 install isort flake8 black -Ue .
      - name: Run isort
        run: isort -c .
      - name: Run flake8
        run: flake8 .
        working-directory: .
      - name: Run black
        run: black --check .
        working-directory: .
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pretix
        run: pip3 install pretix
      - name: Install Dependencies
        run: pip3 install twine check-manifest pretix-plugin-build setuptools build -Ue .
      - name: Run check-manifest
        run: check-manifest .
        working-directory: .
      - name: Build package
        run: python setup.py sdist
        working-directory: .
      - name: Check package
        run: twine check dist/*
        working-directory: .
